#! /bin/sh

# Environment Variable for Java Application
export _JAVA_AWT_WM_NONREPARENTING=1

# Must Have
exec /usr/lib/mate-polkit/polkit-mate-authentication-agent-1 &
[[ -f ~/.Xresources ]] && xrdb -merge -I$HOME ~/.Xresources &
pgrep -x sxhkd > /dev/null || sxhkd &
pgrep -x picom > /dev/null || picom &
pgrep -x dunst > /dev/null || dunst &

# Autostart screenlocking program
# xidlehook --not-when-audio --not-when-fullscreen --timer 600 "betterlockscreen -l dim" "" &

# Change WM Name because Java Apps Hate Non-Reparenting WM
wmname LG3D &

# bspwm Bar using Polybar
$HOME/.config/polybar/launch.sh &

# Autostart Application & Applets using dex
# dex --autostart --environment bspwm

# Wallpaper using feh
~/.fehbg &

# Configuration only for 1 Monitor
bspc monitor -d 1 2 3 4 5 6 7 8 9 10

bspc config border_width         3
bspc config window_gap           10

bspc config split_ratio          0.52
bspc config borderless_monocle   true
bspc config gapless_monocle      true

# Rose Pine Moon Theme
bspc config normal_border_color "#908caa"
bspc config focused_border_color "#9ccfd8"

# bspc rule -a Gimp desktop='^8' state=floating follow=on
bspc rule -a Vivaldi-stable desktop='^1'
bspc rule -a vesktop desktop='^3'
bspc rule -a discord desktop='^3'
bspc rule -a Blueman-manager state=floating
bspc rule -a mplayer2 state=floating
bspc rule -a Kupfer.py focus=on
bspc rule -a Screenkey manage=off
